### ISSUE TITLE
rev_B

### ISSUE THREAD

**Issue by ccai1** [JabirC/DataPhiles#10]
Clear aim of the project, nice touch with the graph
What if a number isn’t divisible by 2, 3, and isn’t prime? Can you order it based on the largest commonality between numbers? (ex: Most numbers are divisible by 7?)

**Comment by DamianWasilewicz** [comment]
Yes! The qualifications that we provided (2, 3, etc.) are just some examples! We will be adding many more commonalities and qualifications
