### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by ccai1** [JabirC/DataPhiles#11]
Your chosen display format is aesthetic, but it’s kind of awkward for their chosen data. It’s hard to minimize the characteristics of a set of numbers to three or four bars. Nevertheless, I think you guys can make it work if you group the numbers based on their most common factor or by the most common characteristic (ex: ends in the ones digit 2).

**Comment by DamianWasilewicz** [comment]
Noted! Those were categories we were planning on using for the bar graphs
