### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by Jiajie-Mai** [JabirC/DataPhiles#12]
I feel that a bar graph/histogram is a good simple and easy way to show the information. However, only having an option for that type of graph might be boring. There should be more options for displaying the information like a line graph for each specific group of numbers (i.e. multiples of 2) and their popularity over time.

**Comment by DamianWasilewicz** [comment]
Noted! We were hoping that the fact that the bar graphs are racing (i.e., that they change over time to reflect the popularity during a different month/year,etc, and overtake each other (moving towards the top, or "first place")) would be exciting, but I'm not sure if that function of the graph was made clear enough in the READ.ME; we will work on that. We are definitely also open to other forms of data visualization and aim to add others, including a line graph!
