### ISSUE TITLE
rev_B

### ISSUE THREAD

**Issue by Jiajie-Mai** [JabirC/DataPhiles#4]
From what I can gather, this project is to discuss the popularity of each number combination for the lottery. Will you add information on winning numbers or not? The README.md has no mention of this and it does seem like it would give the user even more information like which numbers are popular and have a higher chance to win the lottery.

**Comment by DamianWasilewicz** [comment]
Yes, sorry about the lack of clarity; we were indeed talking about using winning numbers, and those are the numbers in our data set. I will look into whether or not there exists a database of the popularity of number combinations in general, winning or not, and see if that's another thing we can factor in. I hope this cleared things up a bit, and we will be editing the README and devlog appropriately.
