### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by Jiajie-Mai** [JabirC/DataPhiles#5]
I assume that the user is using the slider to change to time frame for the numbers, as shown by the image. If this is incorrect, you might need to make it more obvious on what it does. I feel that it is a simple interaction that does allow for some curiosity and exploration but may need more interaction depending on what your view on the project is.

**Comment by DamianWasilewicz** [comment]
The dates will also progress normally without user interaction, to create the animation of the bars "racing" and overtaking each other without user input. The user will be able to change how quickly the time progresses and adjust the slider manually as well. We are going to work on adding more user interaction via the addition of other custom categories, and will look into more ways to expand interactivity.
